platform :ios, '8.0'

target 'WebsocketStompTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for WebsocketStompTest

    pod 'WebsocketStompKit', :git => 'https://github.com/rguldener/WebsocketStompKit.git'

    pod 'SocketRocket', '~> 0.5.1'
    pod 'RealReachability', '~> 1.1.9'
    
end
